// vite-project/app/depositar/[id]/page.tsx
"use client"

import { useState } from "react"
import { useRouter, useParams } from "next/navigation"
import { useSlices, type Slice, type Transaction } from "@/lib/store"

export default function Depositar() {
  const router = useRouter()
  const params = useParams()
  const { slices, updateSlice } = useSlices()
  const sliceId = params.id as string

  const slice = slices.find((s: Slice) => s.id === sliceId)
  const [amount, setAmount] = useState("")

  const handleDeposit = () => {
    if (!amount || Number.parseFloat(amount) <= 0) {
      alert("Ingresa un monto válido")
      return
    }

    if (!slice) return

    const transaction: Transaction = {
      id: Date.now().toString(),
      type: "deposit",
      amount: Number.parseFloat(amount),
      date: Date.now(),
    }

    const updatedSlice: Slice = {
      ...slice,
      amount: slice.amount + Number.parseFloat(amount),
      transactions: [...(slice.transactions || []), transaction],
    }

    updateSlice(slice.id, updatedSlice)
    router.push(`/info-slice/${slice.id}`)
  }

  if (!slice) {
    return <div>No se encontró el slice</div>
  }

  return (
    <div className="min-h-screen p-8" style={{ backgroundColor: "#806CF2" }}>
      <h1
        style={{
          fontSize: "32px",
          fontWeight: "bold",
          color: "#F0EE00",
          fontFamily: "'Stack Sans Text', sans-serif",
          marginBottom: "24px",
          textAlign: "center",
        }}
      >
        Ingresar dinero
      </h1>

      <div
        style={{
          backgroundColor: "white",
          borderRadius: "12px",
          padding: "16px",
          marginBottom: "24px",
          height: "80px",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          maxWidth: "400px",
          marginLeft: "auto",
          marginRight: "auto",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <input
            type="number"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            placeholder="0.00"
            step="0.01"
            style={{
              flex: 1,
              border: "none",
              outline: "none",
              fontFamily: "'Stack Sans Text', sans-serif",
              fontSize: "18px",
              color: "#5E2CBA",
            }}
          />
          <span
            style={{
              fontSize: "16px",
              color: "#5E2CBA",
              fontFamily: "'Stack Sans Text', sans-serif",
              minWidth: "fit-content",
            }}
          >
            {slice.currency}
          </span>
        </div>
      </div>

      <div style={{ display: "flex", gap: "12px", justifyContent: "center", maxWidth: "400px", margin: "0 auto" }}>
        <button
          onClick={handleDeposit}
          style={{
            backgroundColor: "#F0EE00",
            color: "#5E2CBA",
            flex: 1,
            height: "50px",
            borderRadius: "12px",
            fontSize: "16px",
            fontFamily: "'Stack Sans Headline', sans-serif",
            fontWeight: "600",
            border: "none",
            cursor: "pointer",
          }}
        >
          Cargar fondos
        </button>
        <button
          onClick={() => router.push(`/info-slice/${slice.id}`)}
          style={{
            backgroundColor: "rgba(255,255,255,0.3)",
            color: "white",
            flex: 1,
            height: "50px",
            borderRadius: "12px",
            fontSize: "16px",
            fontFamily: "'Stack Sans Text', sans-serif",
            border: "none",
            cursor: "pointer",
          }}
        >
          Cancelar
        </button>
      </div>
    </div>
  )
}

// vite-project/sorc/routes/depositar/[id]/+page.svelte
<script lang="ts">
	import { slices } from '$lib/store';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';

	let slice = $derived.by(() => {
		const id = $page.params.id;
		let found = null;
		slices.subscribe(s => {
			found = s.find(sl => sl.id === id);
		})();
		return found;
	});

	let amount = $state('');

	function deposit() {
		if (!amount || parseFloat(amount) <= 0) {
			alert('Ingresa un monto válido');
			return;
		}

		slices.update(s =>
			s.map(sl =>
				sl.id === slice.id
					? {
							...sl,
							amount: sl.amount + parseFloat(amount)
						}
					: sl
			)
		);

		goto(`/info-slice/${slice.id}`);
	}
</script>

{#if slice}
	<div class="min-h-screen p-8" style="background-color: #806CF2;">
		<h1
			style="
				font-size: 32px;
				font-weight: bold;
				color: #F0EE00;
				font-family: 'Stack Sans Text', sans-serif;
				margin-bottom: 24px;
				text-align: center;
			"
		>
			Ingresar dinero
		</h1>

		<div
			style="
				background-color: white;
				border-radius: 12px;
				padding: 16px;
				margin-bottom: 24px;
				height: 80px;
				display: flex;
				flex-direction: column;
				justify-content: center;
				max-width: 400px;
				margin-left: auto;
				margin-right: auto;
			"
		>
			<div style="display: flex; align-items: center; gap: 12px;">
				<input
					type="number"
					bind:value={amount}
					placeholder="0.00"
					step="0.01"
					style="
						flex: 1;
						border: none;
						outline: none;
						font-family: 'Stack Sans Text', sans-serif;
						font-size: 18px;
						color: #5E2CBA;
					"
				/>
				<span style="font-size: 16px; color: #5E2CBA; font-family: 'Stack Sans Text', sans-serif; min-width: fit-content;">
					{slice.currency}
				</span>
			</div>
		</div>

		<div style="display: flex; gap: 12px; justify-content: center; max-width: 400px; margin: 0 auto;">
			<button
				onclick={deposit}
				style="
					background-color: #F0EE00;
					color: #5E2CBA;
					flex: 1;
					height: 50px;
					border-radius: 12px;
					font-size: 16px;
					font-family: 'Stack Sans Headline', sans-serif;
					font-weight: 600;
					border: none;
					cursor: pointer;
				"
			>
				Cargar fondos
			</button>
			<button
				onclick={() => goto(`/info-slice/${slice.id}`)}
				style="
					background-color: rgba(255,255,255,0.3);
					color: white;
					flex: 1;
					height: 50px;
					border-radius: 12px;
					font-size: 16px;
					font-family: 'Stack Sans Text', sans-serif;
					border: none;
					cursor: pointer;
				"
			>
				Cancelar
			</button>
		</div>
	</div>
{/if}
