// vite-project/sorc/routes/splash.svelte
<script lang="ts">
	// Splash screen component
</script>

<div class="flex items-center justify-center min-h-screen" style="background-color: #806CF2;">
	<svg
		width="142"
		height="142"
		viewBox="0 0 142 142"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
	>
		<!-- Lemon icon SVG -->
		<circle cx="71" cy="71" r="65" fill="#F0EE00" />
		<path
			d="M71 10C71 10 85 25 85 50C85 75 78 85 71 90C64 85 57 75 57 50C57 25 71 10 71 10Z"
			fill="#806CF2"
		/>
		<circle cx="65" cy="65" r="8" fill="#806CF2" opacity="0.4" />
	</svg>
</div>

// vite-project/components/splash.tsx
export default function Splash() {
  return (
    <div className="flex items-center justify-center min-h-screen" style={{ backgroundColor: "#806CF2" }}>
      <svg width="142" height="142" viewBox="0 0 142 142" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="71" cy="71" r="65" fill="#F0EE00" />
        <path d="M71 10C71 10 85 25 85 50C85 75 78 85 71 90C64 85 57 75 57 50C57 25 71 10 71 10Z" fill="#806CF2" />
        <circle cx="65" cy="65" r="8" fill="#806CF2" opacity="0.4" />
      </svg>
    </div>
  )
}
